<script setup lang="ts">
import { computed } from 'vue'

const props=defineProps<{resource:any;channel:any;devices:any[];forwardSlave?:any;readonly:boolean}>()
const emit=defineEmits<{addDevice:[];removeChannel:[];selectDevice:[deviceKey:string];protocolChange:[]}>()
const isForward=computed(()=>props.channel.role==='forward')
const protocol=computed({get:()=>isForward.value?(props.channel.forwardProtocol||props.channel.protocol):props.channel.protocol,set:(value:string)=>{if(isForward.value){props.channel.forwardProtocol=value;props.channel.protocol='none'}else props.channel.protocol=value;emit('protocolChange')}})
function listenField(){return protocol.value==='iec104-server'?'iec104Listen':protocol.value==='iec61850-mms-server'?'iec61850Listen':'modbusListen'}
function defaultListenPort(){return protocol.value==='iec104-server'?2404:protocol.value==='iec61850-mms-server'?102:1502}
const listenPort=computed({get:()=>{const value=String(props.forwardSlave?.[listenField()]||'');return Number(value.slice(value.lastIndexOf(':')+1))||defaultListenPort()},set:(value:number)=>{if(!props.forwardSlave)return;const field=listenField(),current=String(props.forwardSlave[field]||''),host=current.includes(':')?current.slice(0,current.lastIndexOf(':')):'0.0.0.0';props.forwardSlave[field]=`${host||'0.0.0.0'}:${value}`;props.forwardSlave.enabled=true}})
function protocolName(value:string){return ({'iec104-server':'IEC104 服务端','modbus-tcp-slave':'Modbus TCP 从站','iec61850-mms-server':'IEC61850 MMS 服务端','iec61850-goose-publisher':'IEC61850 GOOSE 发布'} as Record<string,string>)[value]||value}
</script>

<template>
  <section class="card legacy-channel-workspace">
    <div class="legacy-section-heading channel-workspace-head"><div><h3>{{channel.name||channel.channelKey}}</h3><p>下挂 {{devices.length}} 台{{isForward?'转发':'采集'}}设备</p><span>绑定资源：{{resource?.name||channel.resourceKey||'-'}}</span></div><div><button :disabled="readonly" @click="emit('addDevice')">新增{{isForward?'转发':'采集'}}设备</button><button class="danger" :disabled="readonly" @click="emit('removeChannel')">删除通道</button></div></div>
    <div class="legacy-field-grid channel-field-grid"><label>通道名称<input v-model.trim="channel.name" :disabled="readonly"/></label><label>通道标识<input :value="channel.channelKey" disabled/></label><label>通道用途<input :value="isForward?'转发':'采集'" disabled/></label><label>{{isForward?'转发协议':'采集协议'}}<select v-model="protocol" :disabled="readonly"><template v-if="isForward"><option value="modbus-tcp-slave">modbus-tcp-slave</option><option value="iec104-server">iec104-server</option><option value="iec61850-mms-server">iec61850-mms-server</option><option value="iec61850-goose-publisher">iec61850-goose-publisher</option></template><template v-else><option value="modbus-rtu">modbus-rtu</option><option value="modbus-tcp">modbus-tcp</option><option value="siemens-s7">siemens-s7</option><option value="iec104">iec104</option><option value="opcua">opcua</option><option value="iec61850">iec61850</option><option value="iec61850-goose">iec61850-goose</option></template></select></label>
      <label v-if="!isForward&&protocol!=='iec104'">采集周期(ms)<input v-model.number="channel.collectIntervalMilliseconds" type="number" min="10" step="10" :placeholder="String((channel.collectIntervalSeconds||1)*1000)" :disabled="readonly"/></label>
      <template v-if="!isForward&&protocol==='iec104'&&channel.iec104"><label>启动总召<select v-model="channel.iec104.generalInterrogationOnStart" :disabled="readonly"><option :value="true">开启</option><option :value="false">关闭</option></select></label><label>周期总召(秒)<input v-model.number="channel.iec104.generalInterrogationIntervalSeconds" type="number" min="0" :disabled="readonly"/></label><label>启动校时<select v-model="channel.iec104.clockSyncOnStart" :disabled="readonly"><option :value="true">开启</option><option :value="false">关闭</option></select></label><label>周期校时(秒)<input v-model.number="channel.iec104.clockSyncIntervalSeconds" type="number" min="0" :disabled="readonly"/></label><label>启动电度召唤<select v-model="channel.iec104.counterInterrogationOnStart" :disabled="readonly"><option :value="true">开启</option><option :value="false">关闭</option></select></label><label>周期电度召唤(秒)<input v-model.number="channel.iec104.counterInterrogationIntervalSeconds" type="number" min="0" :disabled="readonly"/></label><label>采集模式<select v-model="channel.iec104.acquisitionMode" :disabled="readonly"><option value="auto">自动兼容</option><option value="periodic-gi">周期总召</option></select></label></template>
      <label v-if="isForward&&protocol!=='iec61850-goose-publisher'">监听端口<input v-model.number="listenPort" type="number" min="1" max="65535" :placeholder="String(defaultListenPort())" :disabled="readonly"/></label>
    </div>
    <div v-if="isForward&&devices.length" class="forward-channel-devices"><article v-for="device in devices" :key="device.deviceKey"><div><strong>{{device.name||device.deviceKey}}</strong><span>{{protocolName(protocol)}} · {{(device.points||[]).length}} 个转发点位</span></div><button @click="emit('selectDevice',device.deviceKey)">配置</button></article></div>
  </section>
</template>
