<script setup lang="ts">
import { computed } from 'vue'

const props=defineProps<{device:any;readonly:boolean;isForward:boolean}>()
const emit=defineEmits<{test:[];remove:[]}>()
const prefix=computed(()=>props.device.protocol==='opcua'?'opc.tcp://':'')
const stripped=computed(()=>String(props.device.address||'').replace(/^[a-z][a-z0-9+.-]*:\/\//i,''))
const host=computed({get:()=>{const value=stripped.value,index=value.lastIndexOf(':');return index>0?value.slice(0,index):value},set:(value:string)=>{props.device.address=`${prefix.value}${value}${port.value?`:${port.value}`:''}`}})
const port=computed({get:()=>{const value=stripped.value,index=value.lastIndexOf(':');return index>0?value.slice(index+1):''},set:(value:string|number)=>{props.device.address=`${prefix.value}${host.value}${value?`:${value}`:''}`}})
const splitAddress=computed(()=>['modbus-tcp','iec104','siemens-s7','opcua','iec61850'].includes(props.device.protocol))
const isGooseCollect=computed(()=>props.device.protocol==='iec61850-goose')
const isGooseForward=computed(()=>props.device.protocol==='iec61850-goose-publisher')
</script>

<template>
  <div class="exact-device-config"><div class="device-head"><label>设备编号<input :value="device.deviceKey" readonly/></label><label>设备名称<input v-model.trim="device.name" :disabled="readonly"/></label><label>协议<input :value="device.protocol" readonly/></label>
    <template v-if="isForward"><label v-if="device.protocol.includes('modbus')">从站ID<input v-model.number="device.unitId" type="number" min="1" max="247" :disabled="readonly"/></label><label v-if="device.protocol.includes('iec104')">公共地址<input v-model.number="device.commonAddress" type="number" min="1" :disabled="readonly"/></label><label v-if="device.protocol==='iec61850-mms-server'">IED 名称<input v-model.trim="device.iedName" :disabled="readonly"/></label><label v-if="device.protocol==='iec61850-mms-server'">逻辑设备<input v-model.trim="device.logicalDevice" :disabled="readonly"/></label><template v-if="isGooseForward"><label>网卡<input v-model.trim="device.interfaceName" :disabled="readonly"/></label><label>GoCBRef<input v-model.trim="device.goCbRef" class="mono" :disabled="readonly"/></label><label>DataSetRef<input v-model.trim="device.dataSetRef" class="mono" :disabled="readonly"/></label><label>APPID<input v-model.number="device.appId" type="number" min="1" max="65535" :disabled="readonly"/></label><label>目标 MAC<input v-model.trim="device.destinationMac" class="mono" :disabled="readonly"/></label><label>VLAN ID<input v-model.number="device.vlanId" type="number" min="0" max="4094" :disabled="readonly"/></label><label>VLAN 优先级<input v-model.number="device.vlanPriority" type="number" min="0" max="7" :disabled="readonly"/></label><label>允许存活时间(ms)<input v-model.number="device.timeAllowedToLiveMilliseconds" type="number" min="1" :disabled="readonly"/></label><label>ConfRev<input v-model.number="device.confRev" type="number" min="1" :disabled="readonly"/></label></template></template>
    <template v-else><label v-if="device.protocol==='modbus-rtu'">串口<input v-model.trim="device.address" :disabled="readonly"/></label><template v-else-if="splitAddress"><label>设备地址<input v-model.trim="host" :disabled="readonly"/></label><label>端口<input v-model="port" inputmode="numeric" :disabled="readonly"/></label></template><label v-else>{{isGooseCollect?'网卡':'连接地址'}}<input v-model.trim="device.address" :disabled="readonly"/></label><template v-if="isGooseCollect"><label>GoCBRef<input v-model.trim="device.goCbRef" class="mono" :disabled="readonly"/></label><label>DataSetRef<input v-model.trim="device.dataSetRef" class="mono" :disabled="readonly"/></label><label>APPID<input v-model.number="device.appId" type="number" min="1" max="65535" :disabled="readonly"/></label><label>目标 MAC<input v-model.trim="device.destinationMac" class="mono" :disabled="readonly"/></label><label>VLAN ID<input v-model.number="device.vlanId" type="number" min="0" max="4094" :disabled="readonly"/></label><label>VLAN 优先级<input v-model.number="device.vlanPriority" type="number" min="0" max="7" :disabled="readonly"/></label></template><label v-if="device.protocol.startsWith('modbus')">从站ID<input v-model.number="device.slaveId" type="number" min="1" max="247" :disabled="readonly"/></label><label v-if="device.protocol==='iec104'">公共地址<input v-model.number="device.commonAddress" type="number" min="1" :disabled="readonly"/></label><label v-if="device.protocol==='opcua'">用户名<input v-model.trim="device.username" :disabled="readonly"/></label><label v-if="device.protocol==='opcua'">密码<input v-model="device.password" type="password" autocomplete="new-password" :disabled="readonly"/></label><label v-if="device.protocol==='siemens-s7'">Rack<input v-model.number="device.rack" type="number" min="0" :disabled="readonly"/></label><label v-if="device.protocol==='siemens-s7'">Slot<input v-model.number="device.slot" type="number" min="0" :disabled="readonly"/></label><label>超时重连(s)<input v-model.number="device.reconnectIntervalSeconds" type="number" min="1" :disabled="readonly"/></label></template>
    <div class="point-actions"><button v-if="!isForward" @click="emit('test')">测试连接</button><button class="danger" :disabled="readonly" @click="emit('remove')">删除设备</button></div>
  </div></div>
</template>
