<script setup lang="ts">
import { computed } from 'vue'

const props=defineProps<{resource:any;channels:any[];collectDevices:any[];forwardDevices:any[];readonly:boolean}>()
const emit=defineEmits<{addChannel:[];addDevice:[channelKey?:string];selectChannel:[channelKey:string];selectDevice:[channelKey:string,deviceKey:string]}>()

const isSerial=computed(()=>props.resource.type==='serial')
const serialChannel=computed(()=>props.channels[0])
const serialCollectInterval=computed({get:()=>serialChannel.value?.collectIntervalMilliseconds??props.resource.collectIntervalMilliseconds??((serialChannel.value?.collectIntervalSeconds??props.resource.collectIntervalSeconds??1)*1000),set:(value:number)=>{if(serialChannel.value)serialChannel.value.collectIntervalMilliseconds=value;else props.resource.collectIntervalMilliseconds=value}})
const allDevices=computed(()=>[...props.collectDevices,...props.forwardDevices])
const resourceDevices=computed(()=>allDevices.value.filter(device=>props.channels.some(channel=>channel.channelKey===device.channelKey)))
const dnsText=computed({get:()=>Array.isArray(props.resource.network?.dns)?props.resource.network.dns.join(', '):(props.resource.network?.dns||''),set:(value:string)=>{if(props.resource.network)props.resource.network.dns=value.split(',').map(item=>item.trim()).filter(Boolean)}})
function devices(channel:any){const source=channel.role==='forward'?props.forwardDevices:props.collectDevices;return source.filter(device=>device.channelKey===channel.channelKey)}
function protocolName(channel:any){const value=channel.role==='forward'?(channel.forwardProtocol||channel.protocol):channel.protocol;return ({'modbus-rtu':'Modbus RTU','modbus-tcp':'Modbus TCP','siemens-s7':'Siemens S7','iec104':'IEC104','opcua':'OPC UA','iec61850':'IEC 61850 MMS','iec61850-goose':'IEC61850 GOOSE','iec104-server':'IEC104 服务端','modbus-tcp-slave':'Modbus TCP 从站','iec61850-mms-server':'IEC61850 MMS 服务端','iec61850-goose-publisher':'IEC61850 GOOSE 发布'} as Record<string,string>)[value]||value||'-'}
function deviceProtocol(device:any,channel:any){return protocolName({...channel,protocol:device.protocol||channel.protocol,forwardProtocol:channel.role==='forward'?(device.protocol||channel.forwardProtocol):''})}
</script>

<template>
  <section class="card legacy-resource-workspace">
    <div class="legacy-object-hero"><span class="object-icon">{{isSerial?'COM':'LAN'}}</span><div><h3>{{resource.name||resource.resourceKey}}</h3><div class="object-badges"><span>{{isSerial?'串口资源':'网络资源'}}</span><span>{{resource.enabled===false?'已停用':'已启用'}}</span><span>{{isSerial?`${resourceDevices.length} 台设备`:`${channels.length} 个通道`}}</span><span>{{isSerial?'参数与设备':'参数与通道结构'}}</span></div></div></div>
    <div class="legacy-resource-section"><div><h4>{{isSerial?'串口配置':'网口配置'}}</h4><p>{{isSerial?'串口参数对该资源下所有设备生效':'系统网卡与 IPv4 网络参数'}}</p></div>
      <div v-if="isSerial&&resource.serial" class="legacy-field-grid"><label>资源名称<input v-model.trim="resource.name" :disabled="readonly"/></label><label>串口<input v-model.trim="resource.serial.port" :disabled="readonly"/></label><label>波特率<input v-model.number="resource.serial.baudRate" type="number" :disabled="readonly"/></label><label>数据位<input v-model.number="resource.serial.dataBits" type="number" :disabled="readonly"/></label><label>停止位<input v-model.number="resource.serial.stopBits" type="number" step="0.5" :disabled="readonly"/></label><label>校验<select v-model="resource.serial.parity" :disabled="readonly"><option value="none">none</option><option value="odd">odd</option><option value="even">even</option></select></label><label>采集周期(ms)<input v-model.number="serialCollectInterval" type="number" min="10" step="10" :disabled="readonly"/></label></div>
      <div v-else-if="resource.network" class="legacy-field-grid"><label>资源名称<input v-model.trim="resource.name" :disabled="readonly"/></label><label>系统网卡<input v-model.trim="resource.network.interface" :disabled="readonly"/></label><label>网口模式<select v-model="resource.network.mode" :disabled="readonly"><option value="static">static</option><option value="dhcp">dhcp</option></select></label><label>IPv4地址<input v-model.trim="resource.network.ipAddress" :disabled="readonly||resource.network.mode==='dhcp'"/></label><label>前缀长度<input v-model.number="resource.network.prefixLength" type="number" min="1" max="32" :disabled="readonly||resource.network.mode==='dhcp'"/></label><label>默认网关<input v-model.trim="resource.network.gateway" :disabled="readonly||resource.network.mode==='dhcp'"/></label><label class="span-2">DNS服务器<input v-model="dnsText" placeholder="114.114.114.114, 8.8.8.8" :disabled="readonly||resource.network.mode==='dhcp'"/></label></div>
    </div>
    <div class="legacy-resource-section"><div class="legacy-section-heading"><div><h4>{{isSerial?'下挂设备':'通道结构'}}</h4><p>{{isSerial?`${resourceDevices.length} 台设备，点击设备进入配置`:`${channels.length} 个通道，点击通道或设备进入配置`}}</p></div><button :disabled="readonly" @click="isSerial?emit('addDevice',channels[0]?.channelKey):emit('addChannel')">{{isSerial?'新增设备':'新增通道'}}</button></div>
      <div v-if="isSerial" class="legacy-structure-list"><button v-for="device in resourceDevices" :key="device.deviceKey" @click="emit('selectDevice',device.channelKey,device.deviceKey)"><strong>{{device.name||device.deviceKey}}</strong><span>{{deviceProtocol(device,channels.find(item=>item.channelKey===device.channelKey)||{})}} · {{device.address||device.deviceKey}}</span><small>{{(device.points||[]).length}} 个点位</small></button><p v-if="!resourceDevices.length" class="empty-mini">暂无设备</p></div>
      <div v-else class="legacy-channel-structure"><article v-for="channel in channels" :key="channel.channelKey"><button class="channel-structure-card" @click="emit('selectChannel',channel.channelKey)"><strong>{{channel.name||channel.channelKey}}</strong><span>{{channel.role==='forward'?'转发':'采集'}}</span><em>{{protocolName(channel)}} · {{channel.enabled===false?'已停用':'已启用'}}</em><small>{{devices(channel).length}} 台设备</small></button><div class="legacy-structure-list"><button v-for="device in devices(channel)" :key="device.deviceKey" @click="emit('selectDevice',channel.channelKey,device.deviceKey)"><strong>{{device.name||device.deviceKey}}</strong><span>{{deviceProtocol(device,channel)}} · {{channel.role==='forward'?device.deviceKey:(device.address||'-')}}</span><small>{{(device.points||[]).length}} 个点位</small></button><p v-if="!devices(channel).length" class="empty-mini">暂无设备</p></div></article></div>
    </div>
  </section>
</template>
