<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { api } from '../api'
import { confirmAction } from '../confirm'

interface Device { device: string; mountPath: string; kind: string; totalBytes: number; freeBytes: number }
interface StorageStatus { configured: boolean; active: boolean; storagePath: string; maxSizeMB: number; cachePath?: string; cacheBytes?: number; devices: Device[]; historyPath?: string; bytes?: number; files?: number; maxBytes?: number }
const offline = ref<StorageStatus | null>(null), history = ref<StorageStatus | null>(null)
const offlineForm = reactive({ enabled:false, maxSizeMB:16, storagePath:'/media/udisk1' })
const historyForm = reactive({ enabled:false, maxSizeMB:256, storagePath:'/media/udisk1' })
const loading = ref(false), message = ref('')
const formatBytes=(value:number|undefined)=>{const n=Number(value||0);if(n>=1073741824)return(n/1073741824).toFixed(2)+' GB';if(n>=1048576)return(n/1048576).toFixed(2)+' MB';if(n>=1024)return(n/1024).toFixed(1)+' KB';return n+' B'}
async function load(){loading.value=true;try{const [a,b]=await Promise.all([api<StorageStatus>('/api/storage'),api<StorageStatus>('/api/history-storage')]);offline.value=a;history.value=b;Object.assign(offlineForm,{enabled:a.configured,maxSizeMB:a.maxSizeMB||16,storagePath:a.storagePath||'/media/udisk1'});Object.assign(historyForm,{enabled:b.configured,maxSizeMB:b.maxSizeMB||256,storagePath:b.storagePath||'/media/udisk1'});message.value=''}catch(error){message.value=error instanceof Error?error.message:'存储状态读取失败'}finally{loading.value=false}}
async function saveOffline(){loading.value=true;try{offline.value=await api('/api/storage',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(offlineForm)});message.value='断线续存配置已保存。'}catch(error){message.value=error instanceof Error?error.message:'保存失败'}finally{loading.value=false}}
async function saveHistory(){loading.value=true;try{history.value=await api('/api/history-storage',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(historyForm)});message.value='历史数据配置已保存。'}catch(error){message.value=error instanceof Error?error.message:'保存失败'}finally{loading.value=false}}
async function clear(path:string,label:string){if(!await confirmAction({title:`清空${label}`,message:`确认清空${label}？`,detail:'清空操作不可撤销，请确认数据已不再需要。',confirmText:'确认清空',danger:true}))return;try{await api(path,{method:'DELETE'});message.value=`${label}已清空。`;await load()}catch(error){message.value=error instanceof Error?error.message:'清空失败'}}
function exportHistory(){window.location.assign('/api/history-storage/export')}
function openStable(){localStorage.setItem('gateway-active-tab','offline-cache');window.location.assign('/')}
onMounted(load)
</script>
<template><section id="panel-offline-cache"><p v-if="message" class="notice">{{message}}</p><section class="card offline-cache"><div class="section-title"><div><h2>断线续存</h2><p class="meta">{{!offline?.configured?'未启用':offline.active?'外部存储已生效':'已配置但存储未挂载'}}</p></div><div class="point-actions"><span class="pill" :class="offline?.active?'ok':''"><i class="dot"></i><span>{{offline?.active?'运行中':'未启用'}}</span></span><button class="danger" @click="clear('/api/storage','断线缓存')">清除缓存</button><button class="primary" :disabled="loading" @click="saveOffline">保存并应用</button><button @click="load">刷新</button></div></div><div class="wireless-grid storage-form"><label>断线续存<select v-model="offlineForm.enabled"><option :value="true">启用</option><option :value="false">停用</option></select></label><label>容量上限<input v-model.number="offlineForm.maxSizeMB" type="number" min="12" max="16"/></label><label class="wide">存储路径<select v-model="offlineForm.storagePath"><option value="/media/udisk1">/media/udisk1</option><option v-for="device in offline?.devices||[]" :key="device.mountPath" :value="device.mountPath">{{device.kind}} · {{device.mountPath}} · 可用 {{formatBytes(device.freeBytes)}}</option></select></label></div><div class="offline-cache-grid"><div class="offline-cache-item"><span class="label">缓存占用</span><strong>{{formatBytes(offline?.cacheBytes)}}</strong><div class="offline-cache-bar"><span :style="{width:`${Math.min(100,(offline?.cacheBytes||0)/Math.max(1,(offline?.maxSizeMB||16)*1048576)*100)}%`}"></span></div></div><div class="offline-cache-item"><span class="label">容量上限</span><strong>{{offline?.maxSizeMB||16}} MB</strong></div><div class="offline-cache-item"><span class="label">缓存文件</span><code>{{offline?.cachePath||'-'}}</code></div><div class="offline-cache-item"><span class="label">存储介质</span><strong>{{offline?.active?'外接存储':'未挂载'}}</strong><code>{{offline?.storagePath||'-'}}</code></div></div></section>
<section class="card offline-cache history-card"><div class="section-title"><div><h2>历史数据保存</h2><p class="meta">{{!history?.configured?'未启用':history.active?'历史数据正在保存':'已配置但存储未挂载'}}</p></div><div class="point-actions"><span class="pill" :class="history?.active?'ok':''"><i class="dot"></i><span>{{history?.active?'运行中':'未启用'}}</span></span><button @click="exportHistory">导出历史</button><button class="danger" @click="clear('/api/history-storage','历史数据')">清空历史</button><button class="primary" :disabled="loading" @click="saveHistory">保存并应用</button><button @click="load">刷新</button></div></div><div class="wireless-grid storage-form"><label>历史保存<select v-model="historyForm.enabled"><option :value="true">启用</option><option :value="false">停用</option></select></label><label>容量上限<input v-model.number="historyForm.maxSizeMB" type="number" min="64"/></label><label class="wide">存储路径<select v-model="historyForm.storagePath"><option value="/media/udisk1">/media/udisk1</option><option v-for="device in history?.devices||[]" :key="device.mountPath" :value="device.mountPath">{{device.kind}} · {{device.mountPath}} · 可用 {{formatBytes(device.freeBytes)}}</option></select></label></div><div class="offline-cache-grid"><div class="offline-cache-item"><span class="label">历史占用</span><strong>{{formatBytes(history?.bytes)}}</strong></div><div class="offline-cache-item"><span class="label">文件数量</span><strong>{{history?.files||0}}</strong></div><div class="offline-cache-item"><span class="label">历史路径</span><code>{{history?.historyPath||'-'}}</code></div><div class="offline-cache-item"><span class="label">容量上限</span><strong>{{history?.maxSizeMB||256}} MB</strong></div></div></section></section></template>
