<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { api } from '../api'
import { confirmAction } from '../confirm'

type UserItem = { username:string; displayName:string; password?:string; roleKey:string; enabled:boolean }
type RoleItem = { roleKey:string; name:string; description:string; permissions:string[]; builtIn?:boolean }
type PermissionItem = { key:string; name:string; group:string }
type SecurityPayload = { users:UserItem[]; roles:RoleItem[]; permissions:PermissionItem[] }

const loading=ref(false), saving=ref(false), message=ref(''), error=ref('')
const activePanel=ref<'users'|'roles'>('users')
const users=ref<UserItem[]>([]), roles=ref<RoleItem[]>([]), permissions=ref<PermissionItem[]>([])
const editingUser=ref(-1), editingRole=ref(-1)
const userDraft=reactive<UserItem>({username:'',displayName:'',password:'',roleKey:'viewer',enabled:true})
const roleDraft=reactive<RoleItem>({roleKey:'',name:'',description:'',permissions:[]})
const permissionGroups=computed(()=>{const groups=new Map<string,PermissionItem[]>();for(const item of permissions.value){if(!groups.has(item.group))groups.set(item.group,[]);groups.get(item.group)!.push(item)}return [...groups.entries()].map(([name,items])=>({name,items}))})

async function load(){loading.value=true;error.value='';try{const data=await api<SecurityPayload>('/api/security');users.value=(data.users||[]).map(item=>({...item,password:''}));roles.value=(data.roles||[]).map(item=>({...item,permissions:[...(item.permissions||[])]}));permissions.value=data.permissions||[]}catch(cause){error.value=cause instanceof Error?cause.message:'用户和角色读取失败'}finally{loading.value=false}}
function beginUser(index=-1){editingUser.value=index;const item=index>=0?users.value[index]:{username:' ',displayName:'',password:'123456',roleKey:roles.value.find(role=>role.roleKey==='viewer')?.roleKey||roles.value[0]?.roleKey||'',enabled:true};Object.assign(userDraft,item,{password:index>=0?'':item.password})}
function cancelUser(){editingUser.value=-1;Object.assign(userDraft,{username:'',displayName:'',password:'',roleKey:'viewer',enabled:true})}
function commitUser(){const username=userDraft.username.trim();if(!username){error.value='账号不能为空';return}if(editingUser.value<0&&users.value.some(item=>item.username===username)){error.value=`账号已存在：${username}`;return}if(editingUser.value<0&&!userDraft.password){error.value='新增用户必须设置密码';return}const next={...userDraft,username,displayName:userDraft.displayName.trim()};if(editingUser.value>=0)users.value.splice(editingUser.value,1,next);else users.value.push(next);error.value='';cancelUser()}
async function removeUser(index:number){const user=users.value[index];if(!user||user.username==='admin')return;if(await confirmAction({title:'删除账号',message:`确认删除账号“${user.username}”？`,detail:'删除后，该账号将无法继续登录网关。',confirmText:'确认删除',danger:true}))users.value.splice(index,1)}
async function resetPassword(index:number){const user=users.value[index];if(!user||!await confirmAction({title:'重置密码',message:`确认将账号“${user.username}”的密码重置为 123456？`,confirmText:'确认重置'}))return;saving.value=true;error.value='';message.value='';try{const nextUsers=users.value.map((item,itemIndex)=>itemIndex===index?{...item,password:'123456'}:item);await api('/api/security',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({users:nextUsers,roles:roles.value})});message.value=`账号 ${user.username} 的密码已重置为 123456`;await load()}catch(cause){error.value=cause instanceof Error?cause.message:'密码重置失败'}finally{saving.value=false}}
function beginRole(index=-1){editingRole.value=index;const item=index>=0?roles.value[index]:{roleKey:' ',name:'',description:'',permissions:['status.view'],builtIn:false};Object.assign(roleDraft,item,{permissions:[...(item.permissions||[])]})}
function cancelRole(){editingRole.value=-1;Object.assign(roleDraft,{roleKey:'',name:'',description:'',permissions:[],builtIn:false})}
function commitRole(){const roleKey=roleDraft.roleKey.trim(),name=roleDraft.name.trim();if(!roleKey||!name){error.value='角色标识和名称不能为空';return}if(editingRole.value<0&&roles.value.some(item=>item.roleKey===roleKey)){error.value=`角色标识已存在：${roleKey}`;return}const next={...roleDraft,roleKey,name,description:roleDraft.description.trim(),permissions:[...roleDraft.permissions]};if(editingRole.value>=0)roles.value.splice(editingRole.value,1,next);else roles.value.push(next);error.value='';cancelRole()}
async function removeRole(index:number){const role=roles.value[index];if(role.builtIn)return;if(users.value.some(user=>user.roleKey===role.roleKey)){error.value=`角色 ${role.name} 仍被用户使用，不能删除`;return}if(await confirmAction({title:'删除角色',message:`确认删除角色“${role.name}”？`,confirmText:'确认删除',danger:true}))roles.value.splice(index,1)}
function togglePermission(key:string){if(roleDraft.builtIn)return;if(key==='*'){roleDraft.permissions=roleDraft.permissions.includes('*')?[]:['*'];return}roleDraft.permissions=roleDraft.permissions.filter(item=>item!=='*');const index=roleDraft.permissions.indexOf(key);if(index>=0)roleDraft.permissions.splice(index,1);else roleDraft.permissions.push(key)}
async function save(){saving.value=true;error.value='';message.value='';try{await api('/api/security',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({users:users.value,roles:roles.value})});message.value='用户和角色已保存';await load()}catch(cause){error.value=cause instanceof Error?cause.message:'保存失败'}finally{saving.value=false}}
function openStable(){localStorage.setItem('gateway-active-tab','users');window.location.assign('/')}
onMounted(load)
</script>

<template><section id="panel-users"><p v-if="message" class="notice good">{{message}}</p><p v-if="error" class="notice bad">{{error}}</p><section class="card"><div class="section-title"><div><h2>用户管理</h2><p class="meta">按角色分配最小权限；修改密码时才填写密码框，留空会保留原密码。</p></div><div><button :disabled="loading" @click="load">重新加载</button><button class="primary" :disabled="saving||loading" @click="save">{{saving?'保存中…':'保存用户和角色'}}</button></div></div>
<div class="sub-tabs"><button :class="{active:activePanel==='users'}" @click="activePanel='users'">用户管理</button><button :class="{active:activePanel==='roles'}" @click="activePanel='roles'">角色管理</button></div>
<template v-if="activePanel==='users'"><div class="panel-toolbar"><span>共 {{users.length}} 个账号</span><button class="primary" @click="beginUser()">新增账号</button></div><div class="table-scroll"><table><thead><tr><th>账号</th><th>姓名</th><th>角色</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="(user,index) in users" :key="user.username"><td class="mono">{{user.username}}</td><td>{{user.displayName||'-'}}</td><td>{{roles.find(role=>role.roleKey===user.roleKey)?.name||user.roleKey}}</td><td><span class="state-tag" :class="user.enabled?'ok':'bad'">{{user.enabled?'启用':'停用'}}</span></td><td class="row-actions"><button @click="beginUser(index)">编辑</button><button :disabled="saving" @click="resetPassword(index)">重置密码</button><button :disabled="user.username==='admin'" @click="removeUser(index)">删除</button></td></tr></tbody></table></div>
<div v-if="editingUser>=0||userDraft.username||userDraft.password" class="user-edit-modal"><div class="user-edit-dialog"><div><h3>{{editingUser>=0?'编辑账号':'新增账号'}}</h3><p class="meta">新增账号默认密码为 123456，保存后可在列表中重置密码。</p></div><div class="user-edit-grid"><label>账号<input v-model.trim="userDraft.username" :disabled="editingUser>=0" autocomplete="off"/></label><label>姓名<input v-model.trim="userDraft.displayName"/></label><label>角色<select v-model="userDraft.roleKey" :disabled="userDraft.username==='admin'"><option v-for="role in roles" :key="role.roleKey" :value="role.roleKey">{{role.name}}</option></select></label><label>状态<select v-model="userDraft.enabled" :disabled="userDraft.username==='admin'"><option :value="true">启用</option><option :value="false">停用</option></select></label><label>密码<input v-model="userDraft.password" type="password" autocomplete="new-password" placeholder="编辑时留空表示不修改"/></label></div><div class="dialog-actions"><button @click="cancelUser">取消</button><button class="primary" @click="commitUser">保存</button></div></div></div></template>
<template v-else><div class="panel-toolbar"><span>内置角色不可删除，权限由系统固定。</span><button class="primary" @click="beginRole()">新增角色</button></div><div class="role-grid"><article v-for="(role,index) in roles" :key="role.roleKey"><div><strong>{{ role.name }}</strong><span v-if="role.builtIn" class="state-tag">内置</span></div><code>{{ role.roleKey }}</code><p>{{ role.description||'暂无说明' }}</p><small>{{ role.permissions.includes('*')?'全部权限':`${role.permissions.length} 项权限` }}</small><div class="row-actions"><button @click="beginRole(index)">查看{{ role.builtIn?'':'/编辑' }}</button><button :disabled="role.builtIn" @click="removeRole(index)">删除</button></div></article></div>
<div v-if="editingRole>=0||roleDraft.roleKey" class="editor-panel"><h3>{{editingRole>=0?'角色详情':'新增角色'}}</h3><div class="config-grid"><label>角色标识<input v-model.trim="roleDraft.roleKey" :disabled="editingRole>=0" placeholder="例如 engineer"/></label><label>角色名称<input v-model.trim="roleDraft.name" :disabled="roleDraft.builtIn"/></label><label class="span-2">说明<input v-model.trim="roleDraft.description" :disabled="roleDraft.builtIn"/></label></div><div class="permission-groups"><section v-for="group in permissionGroups" :key="group.name"><h4>{{group.name}}</h4><label v-for="item in group.items" :key="item.key" :class="{disabled:roleDraft.builtIn}"><input type="checkbox" :checked="roleDraft.permissions.includes('*')||roleDraft.permissions.includes(item.key)" :disabled="roleDraft.builtIn" @change="togglePermission(item.key)"/><span>{{item.name}}</span><code>{{item.key}}</code></label></section></div><div class="editor-actions"><button @click="cancelRole">关闭</button><button v-if="!roleDraft.builtIn" class="primary" @click="commitRole">确认</button></div></div></template></section></section></template>
