node {
  name = "emqx@127.0.0.1"
  cookie = "emqx50elixir"
  data_dir = "data"
}

cluster {
  name = emqxcl
  discovery_strategy = manual
}

dashboard {
  listeners {
    http.bind = 18083
    https {
      ssl_options {
        certfile = "${EMQX_ETC_DIR}/certs/cert.pem"
        keyfile = "${EMQX_ETC_DIR}/certs/key.pem"
      }
    }
  }
}

authentication = [
  {
    enable = true
    mechanism = password_based
    backend = http
    method = post
    url = "http://host.docker.internal:3100/api/mqtt/auth"
    headers {
      "Content-Type" = "application/json"
      "X-Request-Source" = "EMQX"
    }
    body {
      clientid = "${clientid}"
      username = "${username}"
      password = "${password}"
    }
  }
]

authorization {
  no_match = deny
  deny_action = ignore
  cache { enable = false }
  sources = [
    {
      type = http
      enable = true
      method = post
      url = "http://host.docker.internal:3100/api/mqtt/acl"
      headers {
        "Content-Type" = "application/json"
        "X-Request-Source" = "EMQX"
      }
      body {
        clientid = "${clientid}"
        username = "${username}"
        action = "${action}"
        topic = "${topic}"
      }
    },
    {
      type = file
      enable = true
      path = "etc/acl.conf"
    }
  ]
}
