ALTER TABLE "DeviceMetric"
ADD COLUMN "category" TEXT NOT NULL DEFAULT 'PROPERTY',
ADD COLUMN "accessMode" TEXT NOT NULL DEFAULT 'READ_ONLY',
ADD COLUMN "enabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "sortOrder" INTEGER NOT NULL DEFAULT 0;
